# Generated by Django 6.0.4 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('categoria', models.CharField(choices=[('familia', 'Familia'), ('medico', 'Médico'), ('farmacia', 'Farmacia'), ('vecino', 'Vecino'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
