# Generated by Django 6.0.4 on 2026-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('pastilla', 'Pastilla'), ('medico', 'Médico'), ('llamada', 'Llamada'), ('cumple', 'Cumpleaños'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('hecho', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
